auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:year/:month/:day/:title

title: CodeG.cn
url: http://codeg.cn
feed: /atom.xml
author_info: <a href="http://codeg.cn/">CodeG</a>
